HOME_ROUTE = "/"
LOGIN_ROUTE = "/login"
REGISTER_ROUTE = "/register"
CONTACT_ROUTE = "/contact"
CONTACT_ENTRIES_ROUTE = "/contact/entries"
FQDN_ROUTE = "/fqdn"
PASSWORD_RESET_ROUTE = "/reset_password"