name: Build and Push Container

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - "Dockerfile.production"
      - "compose.prod.yaml"
      - "requirements.txt"
      - assets/
      - reflex_gpt/
      - rxconfig.py
      - alembic.ini
      - alembic/
      - .github/workflows/build.yaml

env:
#  DOCKER_IMAGE: ganesh2257767/altice_utils
  # uncomment if using
   DOCKER_IMAGE: ${{ secrets.DOCKERHUB_REPO }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # For Reflex to build a container,
    # injecting your environment variables at
    # container build time is often required.
    - name: Create build env file
      run: |
         cat << EOF > .build-env
         DB_URL=${{ secrets.DB_URL }}
         CDX_USERNAME=${{ secrets.CDX_USERNAME }}
         CDX_PASSWORD=${{ secrets.CDX_PASSWORD }}
         CHECK_FEASIBILITY_USER=${{ secrets.CHECK_FEASIBILITY_USER }}
         CHECK_FEASIBILITY_PASSWORD=${{ secrets.CHECK_FEASIBILITY_PASSWORD }}
         EOF

    - name: Build and push
      run: |
        docker build -f Dockerfile.production -t ${{ env.DOCKER_IMAGE }}:latest .
        docker tag ${{ env.DOCKER_IMAGE }}:latest ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
        docker push ${{ env.DOCKER_IMAGE }} --all-tags

    - name: Remove build env file
      run: rm .build-env
